# Generated by Django 5.0.1 on 2024-03-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_buyers_products_sellers_delete_buyer_delete_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyers',
            new_name='Buyer',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Sellers',
            new_name='Seller',
        ),
    ]
