# Generated by Django 5.0.1 on 2024-03-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_buyer_buyers_rename_product_products_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyers',
            new_name='Buyer',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Sellers',
            new_name='Seller',
        ),
    ]
