# Generated by Django 5.0.1 on 2024-03-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_buyers_buyer_rename_products_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyer',
            new_name='Buyers',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
        migrations.RenameModel(
            old_name='Seller',
            new_name='Sellers',
        ),
    ]
