# Generated by Django 5.0.1 on 2024-03-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_buyer_buyers_rename_product_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Temp',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
