# Generated by Django 5.0.1 on 2024-03-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_products_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Rating', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Description', models.CharField(max_length=1000)),
                ('Live', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Buyers',
            new_name='Buyer',
        ),
        migrations.RenameModel(
            old_name='Sellers',
            new_name='Seller',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
